openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Contacts Book>
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:32307
  - url: https://nodejs-hw-mongodb-7-pomm.onrender.com
paths:
  /contacts:
    post:
      $ref: ./swagger/paths/contacts/post.yaml
    get:
      $ref: ./swagger/paths/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ./swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ./swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ./swagger/paths/contacts/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
