openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <Contacts Book>
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-6-brjk.onrender.com
paths:
  /contact:
    post:
      $ref: ./swagger/paths/contact/post.yaml
    get:
      $ref: ./swagger/paths/contact/get.yaml
  /contact/{id}:
    get:
      $ref: ./swagger/paths/contact/{id}/get.yaml
    delete:
      $ref: ./swagger/paths/contact/{id}/delete.yaml
    patch:
      $ref: ./swagger/paths/contact/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
